-- Refresh the public, platform-curated catalogue with verified information
-- available for the coming month (27 September – 27 October 2026).
--
-- This deliberately touches only rows published by the platform catalogue.
-- Owner-created sale and breeding announcements remain untouched.

do $$
declare
  platform_owner_id uuid;
begin
  select profile.id
    into platform_owner_id
  from public.profiles profile
  where lower(profile.email) = 'slikrapstelimrec123@gmail.com'
     or profile.role = 'platform_admin'
  order by case
    when lower(profile.email) = 'slikrapstelimrec123@gmail.com' then 0
    else 1
  end, profile.created_at
  limit 1;

  if platform_owner_id is null then
    raise notice 'Curated catalogue was not refreshed: platform owner is absent.';
    return;
  end if;

  -- Retire the previous curated community catalogue so expired offers and
  -- stale service details do not remain visible to users.
  update public.announcements
  set status = 'inactive', updated_at = now()
  where publication_source = 'platform_curated'
    and announcement_type in ('event', 'service', 'offer');

  insert into public.announcements (
    id,
    owner_id,
    pet_id,
    announcement_type,
    title,
    address,
    city,
    description,
    event_date,
    contact_info,
    service_category,
    offer_category,
    price_amount,
    website,
    offer_text,
    valid_from,
    valid_until,
    status,
    moderation_status,
    publication_source,
    publication_tier,
    published_at,
    created_at,
    updated_at
  )
  values
    (
      'c8a57401-3701-4b4e-b0d8-000000000001',
      platform_owner_id,
      null,
      'event',
      'САС «Чарівний поділ-2026»',
      'ВДНГ, Київ',
      'Київ',
      'Сертифікатна виставка собак КСУ, 03.10.2026. Перед поїздкою перевірте програму, реєстрацію та правила на сайті організатора.',
      '2026-10-03 10:00:00+03',
      '+380 67 946 79 99',
      null,
      null,
      null,
      'https://podoldogshow.com.ua/',
      null,
      null,
      null,
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    ),
    (
      'c8a57401-3701-4b4e-b0d8-000000000002',
      platform_owner_id,
      null,
      'event',
      'Vet Case Day — урологія та нефрологія',
      'Mercure Kyiv Congress Hotel, вул. Вадима Гетьмана, 6',
      'Київ',
      'Міжнародна ветеринарна конференція 08–09.10.2026 з офлайн- та онлайн-участю. Програма, квитки й актуальні умови доступні на офіційному сайті.',
      '2026-10-08 09:00:00+03',
      'Реєстрація та квитки — на сайті події',
      null,
      null,
      null,
      'https://www.caseday.vet/',
      null,
      null,
      null,
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    ),
    (
      'c8a57401-3701-4b4e-b0d8-000000000003',
      platform_owner_id,
      null,
      'event',
      'Котики Фест',
      'ВДНГ, павільйон №10',
      'Київ',
      'Фестиваль котів 10.10.2026: лекторій, майстер-класи, благодійний маркет і зона адопції. Вхід за квитками, деталі організатори публікують на сторінці події.',
      '2026-10-10 11:00:00+03',
      'Квитки та умови — на сторінці події',
      null,
      null,
      null,
      'https://theatre.kiev.ua/kotiki-fest-146141/',
      null,
      null,
      null,
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    ),
    (
      'c8a57401-3701-4b4e-b0d8-000000000101',
      platform_owner_id,
      null,
      'service',
      'Zoo&Groomer — грумінг собак і котів',
      'вул. Віктора Некрасова, 8',
      'Київ',
      'Гігієнічний і повний комплекс, породні стрижки та SPA-догляд без седації. Салон приймає щодня; розклад і вільні години перевіряйте під час запису.',
      null,
      '+380 75 679 94 32',
      'groomer',
      null,
      1300,
      'https://www.zooygroomer.com/grooming',
      null,
      null,
      null,
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    ),
    (
      'c8a57401-3701-4b4e-b0d8-000000000102',
      platform_owner_id,
      null,
      'service',
      'Kinolog — дресирування та корекція поведінки',
      'Виїзд по Києву та Україні',
      'Київ',
      'Послух, корекція поведінки, підготовка до спорту й виставок та консультації для власників. На офіційному сайті вказано понад 20 років досвіду; ціни залежать від послуги.',
      null,
      '+380 93 145 55 50 · kinologvkiev@gmail.com',
      'dog_trainer',
      null,
      600,
      'https://kinolog.net.ua/',
      null,
      null,
      null,
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    ),
    (
      'c8a57401-3701-4b4e-b0d8-000000000103',
      platform_owner_id,
      null,
      'service',
      'PetSpot — грумінг-салон для собак і котів',
      'вул. Степана Ковніра, 3',
      'Київ',
      'Стрижка, купання, SPA-догляд і гігієнічні процедури для собак та котів у салоні на Печерську. Актуальні ціни та запис — на сайті салону.',
      null,
      'Запис і контакти — на pet-spot.com.ua',
      'groomer',
      null,
      null,
      'https://pet-spot.com.ua/',
      null,
      null,
      null,
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    ),
    (
      'c8a57401-3701-4b4e-b0d8-000000000104',
      platform_owner_id,
      null,
      'service',
      'INNIKOS Club Hotel — готель для собак і котів',
      'с. Зазим’я, 15 хвилин від Троєщини',
      'Київська область',
      'Окремі кімнати, територія для вигулу, триразовий вигул, пансіон із дресируванням та додатковий догляд. Вільні місця й актуальну ціну потрібно уточнити перед бронюванням.',
      null,
      '+380 93 055 59 11 · innikos.club@gmail.com',
      'dog_hotel',
      null,
      350,
      'https://innikos.com/hotel',
      null,
      null,
      null,
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    ),
    (
      'c8a57401-3701-4b4e-b0d8-000000000201',
      platform_owner_id,
      null,
      'offer',
      'ZooMarket24 — промокод AUTUMN',
      'Онлайн по Україні',
      'Онлайн',
      'Осіння акція зоомагазину ZooMarket24. Перевірте умови, мінімальну суму замовлення та наявність товарів перед оплатою.',
      null,
      'Умови — на сторінці акцій',
      null,
      'shop',
      null,
      'https://zoomarket24.com.ua/promotions',
      '−5% на замовлення від 500 грн за кодом AUTUMN; діє до 31.10.2026.',
      '2026-09-27',
      '2026-10-31',
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    ),
    (
      'c8a57401-3701-4b4e-b0d8-000000000202',
      platform_owner_id,
      null,
      'offer',
      'MasterZoo — «Місія Агента Копито»',
      'Мережа MasterZoo та masterzoo.ua',
      'Україна',
      'Промоакція MasterZoo з розіграшем подарунків для власників тварин. Для участі потрібна картка програми лояльності; обов’язково ознайомтеся з офіційними правилами.',
      null,
      'Офіційні правила — на сайті MasterZoo',
      null,
      'shop',
      null,
      'https://masterzoo.ua/ua/ofitsiini-pravyla-aktsii-misiia-ahenta-kopyto/',
      'Покупка від 700 грн одним чеком у період 15.09–12.10.2026 дає участь у розіграші; умови та винятки — в офіційних правилах.',
      '2026-09-15',
      '2026-10-12',
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    ),
    (
      'c8a57401-3701-4b4e-b0d8-000000000203',
      platform_owner_id,
      null,
      'offer',
      'Zoo&Groomer — −15% на перший грумінг',
      'вул. Віктора Некрасова, 8',
      'Київ',
      'Пропозиція для нових клієнтів салону. Перед записом перевірте вільні години та умови акції на офіційній сторінці.',
      null,
      '+380 75 679 94 32',
      null,
      'other',
      null,
      'https://www.zooygroomer.com/zoo',
      '−15% на будь-яку разову послугу грумінгу для нових клієнтів за промокодом ZOO; діє до 15.10.2026 включно.',
      '2026-09-27',
      '2026-10-15',
      'active',
      'published',
      'platform_curated',
      'standard',
      now(),
      now(),
      now()
    )
  on conflict (id) do update set
    owner_id = excluded.owner_id,
    pet_id = excluded.pet_id,
    announcement_type = excluded.announcement_type,
    title = excluded.title,
    address = excluded.address,
    city = excluded.city,
    description = excluded.description,
    event_date = excluded.event_date,
    contact_info = excluded.contact_info,
    service_category = excluded.service_category,
    offer_category = excluded.offer_category,
    price_amount = excluded.price_amount,
    website = excluded.website,
    offer_text = excluded.offer_text,
    valid_from = excluded.valid_from,
    valid_until = excluded.valid_until,
    status = 'active',
    moderation_status = 'published',
    publication_source = 'platform_curated',
    publication_tier = 'standard',
    updated_at = now();
end
$$;

notify pgrst, 'reload schema';
